import Head from "next/head";
import Footer from "../src/components/Footer/Footer";
import Header from "../src/components/Header/Header";
import MainItem from "../src/components/MainItem/MainItem";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="Welcome." />
      <main className="main-content">
        <MainItem variant="title" content="get together." />
        <MainItem
          variant="text"
          content="Ich finde, es sieht sehr simpel und elegant aus, ich konnte also ein Logo nach meinen Vorschriften erstellen. Ich habe mir zuerst überlegt den Hintergrund des Logos weiss zu lassen, jedoch denke ich, dass die Einprägsamkeit eines Logos auch stark von der Farbe abhängt, also habe ich den Hintergrund eingefärbt. Nun finde ich, dass das Logo auch einprägsam ist.  
Ich werde jedoch an einigen Stellen, wo ein schlichteres Logo benötigt wird, folgendes Logo verwenden:
"
        />
        <MainItem variant="title" content="simpler payment." />
        <MainItem
          variant="text"
          content="Ich finde, es sieht sehr simpel und elegant aus, ich konnte also ein Logo nach meinen Vorschriften erstellen. Ich habe mir zuerst überlegt den Hintergrund des Logos weiss zu lassen, jedoch denke ich, dass die Einprägsamkeit eines Logos auch stark von der Farbe abhängt, also habe ich den Hintergrund eingefärbt. Nun finde ich, dass das Logo auch einprägsam ist.  
Ich werde jedoch an einigen Stellen, wo ein schlichteres Logo benötigt wird, folgendes Logo verwenden:
"
        />
        <MainItem variant="title" content="save time." />
        <MainItem
          variant="text"
          content="Ich finde, es sieht sehr simpel und elegant aus, ich konnte also ein Logo nach meinen Vorschriften erstellen. Ich habe mir zuerst überlegt den Hintergrund des Logos weiss zu lassen, jedoch denke ich, dass die Einprägsamkeit eines Logos auch stark von der Farbe abhängt, also habe ich den Hintergrund eingefärbt. Nun finde ich, dass das Logo auch einprägsam ist.  
Ich werde jedoch an einigen Stellen, wo ein schlichteres Logo benötigt wird, folgendes Logo verwenden:
"
        />
      </main>
      <Footer />
      <style jsx>{``}</style>
    </>
  );
}
